### ISSUE TITLE
Help! Needing TensorFlow version for copyVAE

### ISSUE THREAD

**Issue by ATPs** [mandichen/copyVAE#6]
Hi there,

I'm trying to use copyvae but I'm encountering an error message indicating the script can't find the tensorflow.keras module.

Here's the error I'm seeing:

```
copyvae --help
Traceback (most recent call last):
  File "/data/p/anaconda3/envs/copyVAE/bin/copyvae", line 33, in <module>
    sys.exit(load_entry_point('copyVAE', 'console_scripts', 'copyvae')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/p/anaconda3/envs/copyVAE/bin/copyvae", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/data/p/anaconda3/envs/copyVAE/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/p/anaconda3/envs/copyVAE/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/data/p/copyVAE/copyVAE/copyvae/pipeline.py", line 7, in <module>
    from tensorflow.keras.optimizers import Adam
ModuleNotFoundError: No module named 'tensorflow.keras'

```

I've looked through the documentation but couldn't find specific information about the required TensorFlow version.

Could you please advise which version of TensorFlow I should install to ensure successful use of copyVAE?

Thanks in advance for your help!

**Comment by ivanovaos** [comment]
Hi, I had similar errors. I managed to install with python 3.9 (no default packages) with pip in conda env, but I used pip within conda for whatever else was missing. It doesn't give any error messages after but the run on the provided example fails (ValueError: Obsm 'latent' needs to be of one of np.ndarray...)
